package com.glomowa.footballmatchschedule.model

data class Event(var idEvent: String,
                 var idHomeTeam: String,
                 var idAwayTeam: String,
                 var strLeague: String,
                 var strHomeTeam: String,
                 var strAwayTeam: String,
                 var intHomeScore: String,
                 var intAwayScore: String,
                 var strHomeGoalDetails: String,
                 var strHomeRedCards: String,
                 var strHomeYellowCards: String,
                 var strAwayGoalDetails: String,
                 var strAwayRedCards: String,
                 var strAwayYellowCards: String,
                 var dateEvent: String,
                 var strTime: String
                 )

/*
"events": [
        {
            "idEvent": "576519",
            "idSoccerXML": "389904",
            "strEvent": "Everton vs West Ham",
            "strFilename": "English Premier League 2018-09-15 Everton vs West Ham",
            "strSport": "Soccer",
            "idLeague": "4328",
            "strLeague": "English Premier League",
            "strSeason": "1819",
            "strDescriptionEN": null,
            "strHomeTeam": "Everton",
            "strAwayTeam": "West Ham",
            "intHomeScore": "1",
            "intRound": "5",
            "intAwayScore": "3",
            "intSpectators": "0",
            "strHomeGoalDetails": "45':Gylfi Sigurdsson;",
            "strHomeRedCards": "",
            "strHomeYellowCards": "18':Dominic Calvert-Lewin;90':Bernard;",
            "strHomeLineupGoalkeeper": "Jordan Pickford; ",
            "strHomeLineupDefense": "Jonjoe Kenny; Mason Holgate; Kurt Zouma; Lucas Digne; ",
            "strHomeLineupMidfield": "Idrissa Gana Gueye; Morgan Schneiderlin; Theo Walcott; Gylfi Sigurdsson; Bernard; ",
            "strHomeLineupForward": "Cenk Tosun; ",
            "strHomeLineupSubstitutes": "Maarten Stekelenburg; Leighton Baines; Baye Oumar Niasse; Bernard; Tom Davies; Kieran Dowell; Ademola Lookman; ",
            "strHomeFormation": "",
            "strAwayRedCards": "",
            "strAwayYellowCards": "40':Arthur Masuaku;51':Andriy Yarmolenko;53':Pablo Zabaleta;75':Declan Rice;90':Robert Snodgrass;",
            "strAwayGoalDetails": "11':Andriy Yarmolenko;31':Andriy Yarmolenko;61':Marko Arnautovic;",
            "strAwayLineupGoalkeeper": "Lukasz Fabianski; ",
            "strAwayLineupDefense": "Ryan Fredericks; Fabian Balbuena; Issa Diop; Aaron Cresswell; ",
            "strAwayLineupMidfield": "Declan Rice; Carlos Sanchez; Andriy Yarmolenko; Felipe Anderson; Michail Antonio; ",
            "strAwayLineupForward": "Marko Arnautovic; ",
            "strAwayLineupSubstitutes": "Adrian; Aaron Cresswell; Angelo Ogbonna; Carlos Sanchez; Robert Snodgrass; Michail Antonio; Lucas Perez; ",
            "strAwayFormation": "",
            "intHomeShots": null,
            "intAwayShots": null,
            "dateEvent": "2018-09-16",
            "strDate": "16/09/18",
            "strTime": "15:00:00+00:00",
        }
    ]
 */